# -*- coding: utf-8 -*-
"""Telecom Customer Behaviour and Churn Risk analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LTEHZ5BMamJ-G-CgqnT4YcQk9KNjLl0g
"""

from google.colab import files
uploaded=files.upload()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv("test.csv")

df.head()

df.info()

df.describe()

df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')

print("Missing Values:")
print(df.isnull().sum())
df.dropna(inplace=True)

df.drop_duplicates(inplace=True)
print("\nDataset Shape:", df.shape)

print("\nDescriptive Statistics:")
display(df.describe())

numerical_cols = df.select_dtypes(include=np.number).columns

for col in numerical_cols:
    plt.figure(figsize=(6,4))
    sns.histplot(df[col], kde=True)
    plt.title(f'Distribution of {col}')
    plt.show()

plt.figure(figsize=(8,6))
corr = df[numerical_cols].corr()

sns.heatmap(corr, annot=True, cmap='coolwarm')
plt.title("Correlation Heatmap")
plt.show()

revenue_by_contract = df.groupby('Contract')['TotalCharges'].sum()

plt.figure(figsize=(6,4))
sns.barplot(x=revenue_by_contract.index,
            y=revenue_by_contract.values)

plt.title("Revenue by Contract Type")
plt.ylabel("Total Revenue")
plt.show()

at_risk = df[
    (df['Contract'] == 'Month-to-month') &
    (df['tenure'] <= 12)
]

print("\nAt Risk Customers:", len(at_risk))

# Revenue at risk
risk_revenue = at_risk['MonthlyCharges'].sum()

print("Monthly Revenue At Risk:", risk_revenue)

plt.figure(figsize=(6,4))

sns.boxplot(x='Contract',
            y='MonthlyCharges',
            data=df)

plt.title("Monthly Charges by Contract")
plt.show()

print("""
Key Insights:
1. Month-to-month customers show higher churn risk.
2. Customers with longer tenure generate more revenue.
3. Higher monthly charges contribute to higher total revenue.
4. Long-term contracts improve customer retention.
""")